schema: "classroom50/repo-config/v1"
classroom: "ds-turma-6a"
assignment: "aula05-cadastro-alunos-dupla"
owner:
  username: "GabrielGB-markerting"
  id: 211169195
  accepted_at: "2026-08-28T12:02:32Z"
source:
  owner: "desenvolvimento-sistemas-2026-2"
  owner_id: 318238261
  repo: "aula05-cadastro-alunos-dupla-template"
  branch: "main"
